{% set name = "h5py" %}
{% set version = "3.8.0" %}
{% set build = 0 %}

# mpi must be defined for conda-smithy lint
{% set mpi = mpi or 'nompi' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 1ec05e67b246a50142762de1bd008022366562d749fd508417ba3286a4a692ad

build:
  skip: True  # [py<=36]
  number: {{ build }}

requirements:
  build:
    - {{ compiler("c") }}
  host:
    - python
    - cython >=0.29.15
    - hdf5
    - numpy
    - pip
    - pkgconfig
    - setuptools
    - wheel
  run:
    - python
    # hdf5 >=1.10.4 has run_exports
    - hdf5
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - h5py
    - h5py.tests
    - h5py.tests.data_files
    - h5py.tests.test_vds
  requires:
    - pip
    - pytest
    - pytest-mpi
    - curl
  commands:
    - pip check

about:
  home: https://www.h5py.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: licenses/license.txt
  summary: Read and write HDF5 files from Python
  dev_url: https://github.com/h5py/h5py
  doc_url: https://docs.h5py.org/en/stable/

extra:
  recipe-maintainers:
    - jakirkham
    - tacaswell
    - ocefpaf
    - minrk
    - scopatz
