{% set version = "3.2.1" %}

package:
  name: h5py
  version: {{ version }}

source:
  url: https://github.com/h5py/h5py/archive/{{ version }}.tar.gz
  sha256: bc3d12b0a14deecf67b1c3786e528a6c5a1094150d46c07d0ba42e9d99751fa0
  patches:  # [not osx]
    - disable-tests.patch  # [not osx]

build:
  number: 0

requirements:
  build:
    - {{ compiler("c") }}
  host:
    - python
    - pip
    - numpy-devel  {{ numpy }}
    - hdf5
    - cython
    - six
    - pkgconfig
  run:
    - python
    - hdf5
    - six
    - unittest2  # [py26 or py27]
    - pyreadline  # [win]

test:
  requires:
    - pytest
  imports:
    - h5py

about:
  home: http://www.h5py.org/
  license: BSD-3-Clause
  license_file: licenses/license.txt
  summary: Read and write HDF5 files from Python.
  description: |
    H5py uses straightforward NumPy and Python metaphors, like dictionary and
    NumPy array syntax.
  doc_url: http://docs.h5py.org
  dev_url: https://github.com/h5py/h5py

extra:
  recipe-maintainers:
    - jakirkham
    - pitrou
    - tacaswell
    - ocefpaf
