{% set version = "3.3.0" %}
{% set build = 0 %}

# mpi must be defined for conda-smithy lint
{% set mpi = mpi or 'nompi' %}

package:
  name: h5py
  version: {{ version }}

source:
  url: https://github.com/h5py/h5py/archive/{{ version }}.tar.gz
  sha256: d34e362d6e278d583a8fbcdd6628bdb2af4cfa4077d373d767d79cd7911af2b1
  patches:
    # override setup.py specified minimum compatible numpy versions
    # we take care of those via numpy pinning below
    - adjust-minimum-numpy-run-versions.patch
    - osx-arm64.diff    # [osx and arm64]
    - osx-arm64-hdf5.diff    # [osx and arm64]

build:
  skip: True  # [py<=36]
  number: {{ build }}
  script_env:
    - HDF5_HAS_ROS3=1  # [osx and arm64]

requirements:
  build:
    - {{ compiler("c") }}
  host:
    - python
    - pip
    - numpy
    - hdf5
    - cython >=0.29.0  # [py<38]
    - cython >=0.29.14  # [py>=38]
    - pkgconfig
  run:
    - python
    - cached-property
    - {{ pin_compatible('numpy') }}
    # hdf5 >=1.10.4 has run_exports
    - hdf5
    - pyreadline  # [win]

test:
  imports:
    - h5py
  commands:
    - pip check
  requires:
    - pip
    - pytest
    - pytest-mpi

about:
  home: http://www.h5py.org/
  license: BSD-3-Clause
  license_file: licenses/license.txt
  summary: Read and write HDF5 files from Python
  dev_url: https://github.com/h5py/h5py

extra:
  recipe-maintainers:
    - jakirkham
    - tacaswell
    - ocefpaf
    - minrk
    - scopatz
