{% set name = "h5py" %}
{% set version = "3.7.0" %}
{% set build = 0 %}

# mpi must be defined for conda-smithy lint
{% set mpi = mpi or 'nompi' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 71ee0e0a25d6acc5e99ff13c287cae006604f6054dd9b60c352d0216e5d6b6f4
  patches:
    - osx-arm64.diff    # [osx and arm64]
    - osx-arm64-hdf5.diff    # [osx and arm64]

build:
  skip: True  # [py<=36]
  number: {{ build }}
  script_env:
    - HDF5_HAS_ROS3=1  # [osx and arm64]

requirements:
  build:
    - {{ compiler("c") }}
    - m2-patch  # [win]
    - patch     # [not win]
  host:
    - python
    - cython >=0.29.15
    - hdf5
    - numpy
    - pip
    - pkgconfig
    - setuptools
    - wheel
  run:
    - python
    # hdf5 >=1.10.4 has run_exports
    - hdf5
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - h5py
    - h5py.tests
    - h5py.tests.data_files
    - h5py.tests.test_vds
  requires:
    - pip
    - pytest
    - pytest-mpi
    - curl
  commands:
    - pip check

about:
  home: https://www.h5py.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: licenses/license.txt
  summary: Read and write HDF5 files from Python
  dev_url: https://github.com/h5py/h5py
  doc_url: https://docs.h5py.org/en/stable/

extra:
  recipe-maintainers:
    - jakirkham
    - tacaswell
    - ocefpaf
    - minrk
    - scopatz
