{% set name = "h5py" %}
{% set version = "3.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/{{ version }}.tar.gz
  sha256: d16d0f02e24aed3ba8eb59e406aa44a24f6295c4ad7d85ad4ec6bc0ea176a24e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  build:
    - {{ compiler("c") }}
  host:
    - python
    - cython >=0.29.31,<4
    - hdf5 {{ hdf5 }}
    - numpy >=2.0.0,<3
    - pip
    - pkgconfig
    # decrease setuptools version due to: https://github.com/AnacondaRecipes/numpy-feedstock/blob/master/recipe/meta.yaml#L63
    - setuptools <74
    # "mpi4py ==3.1.1; python_version<'3.11'"
    - mpi4py <=3.1.4  # [py<311]
    # "mpi4py ==3.1.4; python_version=='3.11.*'"
    - mpi4py ==3.1.4  # [py==311]
    # "mpi4py ==3.1.6; python_version=='3.12.*'"
    # "mpi4py ==4.0.1; python_version>='3.13'"
    - mpi4py >=4.0.1  # [py>311]
  run:
    - python
    - numpy >=1.19.3
    - mpi4py >=3.1.1

# Failed: DID NOT RAISE <class 'PermissionError'>
{% set test_to_skip = "test_append_permissions" %}

test:
  imports:
    - h5py
    - h5py._hl
    - h5py._selector
    - h5py.h5py_warnings
  requires:
    - pip
    - pytest
    - pytest-mpi
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -k "not {{ test_to_skip }}" --pyargs h5py.tests

about:
  home: https://www.h5py.org
  summary: The h5py package is a Pythonic interface to the HDF5 binary data format.
  license: BSD-3-Clause
  license_family: BSD
  license_file: licenses/license.txt
  description: |
    HDF5 lets you store huge amounts of numerical data, and easily manipulate that data from NumPy.
    For example, you can slice into multi-terabyte datasets stored on disk, as if they were real NumPy arrays.
    Thousands of datasets can be stored in a single file, categorized and tagged however you want.
  dev_url: https://github.com/h5py/h5py
  doc_url: https://docs.h5py.org

extra:
  recipe-maintainers:
    - jakirkham
    - tacaswell
    - ocefpaf
    - minrk
    - scopatz
  skip-lints:
  # wheel is not needed if setuptools>7
  - missing_wheel