{% set version = "3.5.0" %}
{% set build = 0 %}

# mpi must be defined for conda-smithy lint
{% set mpi = mpi or 'nompi' %}

{% if mpi == 'nompi' %}
# prefer nompi builds via a build number offset
{% set build = build + 100 %}
{% endif %}

package:
  name: h5py
  version: {{ version }}

source:
  url: https://github.com/h5py/h5py/archive/{{ version }}.tar.gz
  sha256: b9876e15540b8bf1eb434de8e3751721146f7d0e015f9b235ec11fd774f82616
  patches:
    # override setup.py specified minimum compatible numpy versions
    # we take care of those via numpy pinning below
    - adjust-minimum-numpy-run-versions.patch
    - osx-arm64.diff    # [osx and arm64]
    - osx-arm64-hdf5.diff    # [osx and arm64]

build:
  skip: True  # [py<=36]
  number: {{ build }}
  {% if mpi != 'nompi' %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  # add build string so packages can depend on
  # mpi or nompi variants
  # dependencies:
  # `pkg * mpi_mpich_*` for mpich
  # `hdf5 * mpi_*` for any mpi
  # `hdf5 * nompi_*` for no mpi
  string: {{ mpi_prefix }}_py{{ py }}h{{ PKG_HASH }}_{{ build }}
  script_env:
    - HDF5_HAS_ROS3=1  # [osx and arm64]

requirements:
  build:
    - {{ compiler("c") }}
    - m2-patch  # [win]
    - patch     # [not win]
    - {{ mpi }}  # [mpi == 'openmpi' and build_platform != target_platform]
  host:
    - python
    - pip
    - numpy
    - {{ mpi }}  # [mpi != 'nompi']
    - mpi4py >=3.0  # [mpi != 'nompi']
    # need to list hdf5 twice to get version pinning from conda_build_config
    # and build pinning from {{ mpi_prefix }}
    - hdf5
    - hdf5 * {{ mpi_prefix }}_*
    - cython >=0.29.0  # [py<38]
    - cython >=0.29.14  # [py==38]
    - cython >=0.29.15  # [py>=38]
    - pkgconfig
    - setuptools
    - wheel
  run:
    - python
    - cached-property  # [py<38]
    - {{ pin_compatible('numpy') }}
    - {{ mpi }}  # [mpi != 'nompi']
    - mpi4py >=3.0  # [mpi != 'nompi']
    # hdf5 >=1.10.4 has run_exports
    - hdf5
    - pyreadline  # [win]

test:
  imports:
    - h5py
  requires:
    - pip
    - pytest
    - pytest-mpi
    - curl
  commands:
    - pip check

about:
  home: http://www.h5py.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: licenses/license.txt
  summary: Read and write HDF5 files from Python
  dev_url: https://github.com/h5py/h5py

extra:
  recipe-maintainers:
    - jakirkham
    - tacaswell
    - ocefpaf
    - minrk
    - scopatz
