{% set version = "3.1.0" %}

package:
  name: h5py
  version: {{ version }}

source:
  url: https://github.com/h5py/h5py/archive/{{ version }}.tar.gz
  sha256: 62fdd5153a699e3dd7393d965ee3721a99c4635621bdad4580d34c496d6e3a5b

build:
  number: 0

requirements:
  build:
    - {{ compiler("c") }}
  host:
    - python
    - pip
    - numpy-devel  {{ numpy }}
    - hdf5
    - cython
    - six
    - pkgconfig
  run:
    - python
    - hdf5
    - six
    - unittest2  # [py26 or py27]
    - pyreadline  # [win]

test:
  requires:
    - pytest
  imports:
    - h5py

about:
  home: http://www.h5py.org/
  license: BSD-3-Clause
  license_file: licenses/license.txt
  summary: Read and write HDF5 files from Python.
  description: |
    H5py uses straightforward NumPy and Python metaphors, like dictionary and
    NumPy array syntax.
  doc_url: http://docs.h5py.org
  dev_url: https://github.com/h5py/h5py

extra:
  recipe-maintainers:
    - jakirkham
    - pitrou
    - tacaswell
    - ocefpaf
