{% set name = "h5py" %}
{% set version = "3.12.1" %}

# mpi must be defined for conda-smithy lint
{% set mpi = mpi or 'nompi' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/{{ version }}.tar.gz
  sha256: ee8d25e6cc6275779a2727258bcce9f2296a58b6e5ccf4cdc467a3c3a97b56b2

build:
  skip: True  # [py<39]
  number: 1

requirements:
  build:
    - {{ compiler("c") }}
  host:
    - python
    - cython >=0.29.31,<4
    - hdf5 {{ hdf5 }}
    - numpy >=2.0.0, <3
    - pip
    - pkgconfig
    - setuptools >=61
    - wheel
  run:
    - python
    - hdf5  # exact pin handled through hdf5 run_exports
    - numpy >=1.19.3, <3

test:
  imports:
    - h5py
    - h5py.tests
    - h5py.tests.data_files
    - h5py.tests.test_vds
  requires:
    - pip
    - pytest
    - pytest-mpi
    - curl
  commands:
    - pip check

about:
  home: https://www.h5py.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: licenses/license.txt
  description: Read and write HDF5 files from Python
  summary: Read and write HDF5 files from Python
  dev_url: https://github.com/h5py/h5py
  doc_url: https://docs.h5py.org

extra:
  recipe-maintainers:
    - jakirkham
    - tacaswell
    - ocefpaf
    - minrk
    - scopatz
  # Skipping these, are not relevant to this package
  skip-lints:
    - invalid_url
    - host_section_needs_exact_pinnings
    - pip_install_args