{% set version = "2.7.0" %}

package:
  name: h5py
  version: {{ version }}

source:
  fn: h5py-{{ version }}.tar.gz
  url: https://github.com/h5py/h5py/archive/{{ version }}.tar.gz
  sha256: fff3a878c6adfa1b4f5c30b558a295d52dd4fee9174128c626ef416dec1b536b

build:
  number: 1

requirements:
  host:
    - hdf5
    - python
    - setuptools
    - numpy
    - cython
    - six
    - pkgconfig

  build:
    - {{ compiler('c') }}

  run:
    - hdf5
    - numpy
    - python
    - six
    - unittest2    # [py26]

test:
  imports:
    - h5py

about:
  home: http://www.h5py.org/
  license: BSD 3-Clause
  license_file: licenses/license.txt
  summary: Read and write HDF5 files from Python.

extra:
  recipe-maintainers:
    - jakirkham
    - pitrou
    - tacaswell
